// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Ginkgo Backup

package simple

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

// The files under testdata/ are hand-authored format fixtures, deliberately
// NOT generated by the current code: they pin the on-disk manifest format
// (field names, v1 legacy layout, FlexTime numeric units, checksum sidecar
// convention, manifest filename convention). If a struct tag rename, a
// layout change, or a FlexTime heuristic change breaks compatibility with
// existing repositories, these tests fail instead of silently orphaning
// every backup made by an older release.
//
// Regenerating a fixture after an INTENTIONAL format change also requires
// recomputing its .sha256 sidecar:
//
//	sha256sum testdata/manifest_v2.json > testdata/manifest_v2.json.sha256

func loadFixtureManifest(t *testing.T, name string) *Manifest {
	t.Helper()
	path := filepath.Join("testdata", name)
	m, err := LoadManifest(path)
	if err != nil {
		t.Fatalf("LoadManifest(%s): %v", name, err)
	}
	return m
}

// TestManifestV2FixtureFormat pins the v2 on-disk manifest schema. Every
// assertion doubles as a field-name pin: if a json tag is renamed, the
// fixture value no longer decodes into the struct and the test fails.
func TestManifestV2FixtureFormat(t *testing.T) {
	m := loadFixtureManifest(t, "manifest_v2.json")

	if m.Version != 2 {
		t.Fatalf("version = %d, want 2", m.Version)
	}
	if m.SourceID != 7 {
		t.Fatalf("sourceId = %d, want 7", m.SourceID)
	}
	if m.CloudID != "fixture-device/7" {
		t.Fatalf("cloudId = %q, want %q", m.CloudID, "fixture-device/7")
	}
	if m.DeviceID != "fixture-device" {
		t.Fatalf("deviceId = %q, want %q", m.DeviceID, "fixture-device")
	}
	if m.SourceName != "fixture-source" {
		t.Fatalf("sourceName = %q", m.SourceName)
	}
	if m.Timestamp != "2026-05-11T08:00:00Z" {
		t.Fatalf("timestamp = %q", m.Timestamp)
	}

	// Root-level file with string mtime.
	root, ok := m.FindFile("report.txt")
	if !ok {
		t.Fatal("report.txt not found in manifest")
	}
	if root.ContentHash != "1111111111111111111111111111111111111111111111111111111111111111" {
		t.Fatalf("report.txt contentHash = %q", root.ContentHash)
	}
	if root.Size != 123 {
		t.Fatalf("report.txt size = %d, want 123", root.Size)
	}
	if got := root.MtimeTime().UTC().Format(time.RFC3339); got != "2026-05-11T08:00:00Z" {
		t.Fatalf("report.txt mtime = %s, want 2026-05-11T08:00:00Z", got)
	}

	// Chunked file with numeric nanosecond mtime (FlexTime unit heuristic).
	bin, ok := m.FindFile("docs/data.bin")
	if !ok {
		t.Fatal("docs/data.bin not found in manifest")
	}
	if len(bin.Chunks) != 2 {
		t.Fatalf("docs/data.bin chunks = %d, want 2", len(bin.Chunks))
	}
	if bin.Chunks[0].Hash != "3333333333333333333333333333333333333333333333333333333333333333" ||
		bin.Chunks[0].Size != 4096 ||
		bin.Chunks[1].Size != 471 {
		t.Fatalf("docs/data.bin chunk refs drifted: %+v", bin.Chunks)
	}
	if got := bin.MtimeTime().UTC().Format(time.RFC3339); got != "2026-05-11T08:00:00Z" {
		t.Fatalf("docs/data.bin nanos mtime = %s, want 2026-05-11T08:00:00Z", got)
	}

	// File with numeric millisecond mtime must land on the same instant.
	millis, ok := m.FindFile("docs/legacy-millis.txt")
	if !ok {
		t.Fatal("docs/legacy-millis.txt not found in manifest")
	}
	if got := millis.MtimeTime().UTC().Format(time.RFC3339); got != "2026-05-11T08:00:00Z" {
		t.Fatalf("docs/legacy-millis.txt millis mtime = %s, want 2026-05-11T08:00:00Z", got)
	}

	// Empty directory entry survives.
	if _, ok := m.Dirs["empty-dir"]; !ok {
		t.Fatal("empty-dir dir entry lost")
	}

	// Stats field names pin (incl. deletedFiles and scanErrors).
	if m.Stats.FileCount != 3 {
		t.Fatalf("stats.fileCount = %d, want 3", m.Stats.FileCount)
	}
	if m.Stats.TotalSize != 4698 {
		t.Fatalf("stats.totalSize = %d, want 4698", m.Stats.TotalSize)
	}
	if m.Stats.DeletedFiles != 1 {
		t.Fatalf("stats.deletedFiles = %d, want 1", m.Stats.DeletedFiles)
	}
	if m.Stats.ScanErrors != 2 {
		t.Fatalf("stats.scanErrors = %d, want 2", m.Stats.ScanErrors)
	}

	// BuildFileMap reconstructs full slash paths.
	if _, ok := m.BuildFileMap()["docs/data.bin"]; !ok {
		t.Fatal("BuildFileMap missing docs/data.bin")
	}

	// Alive index prefers chunk hashes and falls back to contentHash:
	// 1 (report.txt) + 2 (data.bin chunks) + 1 (legacy-millis.txt).
	idx := ManifestToAliveIndex(m)
	if idx.Version != 1 || len(idx.Hashes) != 4 {
		t.Fatalf("alive index = {version:%d hashes:%d}, want {1, 4}", idx.Version, len(idx.Hashes))
	}
}

// TestManifestV1FixtureMigration pins the v1 legacy layout (flat files
// array with path field + emptyDirs) and its migration to the v2 Dirs
// structure.
func TestManifestV1FixtureMigration(t *testing.T) {
	m := loadFixtureManifest(t, "manifest_v1.json")

	if m.Version != 2 {
		t.Fatalf("post-migration version = %d, want 2", m.Version)
	}
	if m.Stats.FileCount != 2 {
		t.Fatalf("stats.fileCount = %d, want 2", m.Stats.FileCount)
	}
	if m.Stats.TotalSize != 300 {
		t.Fatalf("stats.totalSize = %d, want 300", m.Stats.TotalSize)
	}

	readme, ok := m.FindFile("readme.md")
	if !ok {
		t.Fatal("readme.md not found after migration")
	}
	if readme.Size != 100 {
		t.Fatalf("readme.md size = %d, want 100", readme.Size)
	}
	if got := readme.MtimeTime().UTC().Format(time.RFC3339); got != "2026-05-11T08:00:00Z" {
		t.Fatalf("readme.md mtime = %s, want 2026-05-11T08:00:00Z", got)
	}

	notes, ok := m.FindFile("docs/notes.txt")
	if !ok {
		t.Fatal("docs/notes.txt not found after migration")
	}
	if len(notes.Chunks) != 1 || notes.Chunks[0].Size != 200 {
		t.Fatalf("docs/notes.txt chunks drifted: %+v", notes.Chunks)
	}

	// Empty dir migrated into the Dirs map.
	if _, ok := m.Dirs["docs/empty"]; !ok {
		t.Fatal("docs/empty dir entry lost in migration")
	}

	// The streaming alive-hash extractor must understand the legacy flat
	// layout too (readme contentHash + notes chunk hash).
	data, err := os.ReadFile(filepath.Join("testdata", "manifest_v1.json"))
	if err != nil {
		t.Fatalf("read v1 fixture: %v", err)
	}
	hashes, err := extractHashesFromJSON(data)
	if err != nil {
		t.Fatalf("extractHashesFromJSON(v1): %v", err)
	}
	if len(hashes) != 2 {
		t.Fatalf("v1 alive hashes = %d, want 2", len(hashes))
	}
}

// TestManifestFilenameConvention pins the on-disk manifest filename
// convention {unixSec}_{deviceID}.json.zst and the same-second conflict
// suffix {unixSec}_{deviceID}_{6hex}.json.zst.
func TestManifestFilenameConvention(t *testing.T) {
	cases := []struct {
		name string
		want string
	}{
		{"1778486400_fixture-device.json.zst", "2026-05-11T08:00:00Z"},
		{"1778486400_fixture-device_ab12cd.json.zst", "2026-05-11T08:00:00Z"},
		{"1778486400_fixture-device.json", "2026-05-11T08:00:00Z"},
	}
	for _, c := range cases {
		got, err := ParseManifestFilenameTimestamp(c.name)
		if err != nil {
			t.Fatalf("ParseManifestFilenameTimestamp(%q): %v", c.name, err)
		}
		if got != c.want {
			t.Fatalf("ParseManifestFilenameTimestamp(%q) = %q, want %q", c.name, got, c.want)
		}
	}

	if _, err := ParseManifestFilenameTimestamp("not-a-timestamp.json.zst"); err == nil {
		t.Fatal("expected error for non-timestamp filename")
	}
}
